name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, xml, ctype, json, tokenizer, curl, fileinfo

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Copy .env example
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Laravel tests
        run: php artisan test
